-- ============================================================
-- Zythologue - Schéma de la base de données
-- PostgreSQL 18
-- ============================================================

-- Drop dans l'ordre inverse des dépendances pour réexécution propre
DROP TABLE IF EXISTS beer_ingredient CASCADE;
DROP TABLE IF EXISTS beer_category CASCADE;
DROP TABLE IF EXISTS brewery_favorite CASCADE;
DROP TABLE IF EXISTS beer_favorite CASCADE;
DROP TABLE IF EXISTS brewery_photo CASCADE;
DROP TABLE IF EXISTS beer_photo CASCADE;
DROP TABLE IF EXISTS brewery_review CASCADE;
DROP TABLE IF EXISTS beer_review CASCADE;
DROP TABLE IF EXISTS beer_log CASCADE;
DROP TABLE IF EXISTS beer CASCADE;
DROP TABLE IF EXISTS ingredient CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS brewery CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

-- ============================================================
-- Tables indépendantes (sans FK sortante)
-- ============================================================

-- "user" est un mot réservé PostgreSQL, on le quote
CREATE TABLE IF NOT EXISTS "user" (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lastname    VARCHAR(100)  NOT NULL,
    firstname   VARCHAR(100)  NOT NULL,
    email       VARCHAR(255)  NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    birthdate   DATE          NOT NULL,
    role        VARCHAR(10)   NOT NULL DEFAULT 'client'
                    CHECK (role IN ('client', 'admin')),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS brewery (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL UNIQUE,
    description TEXT          NOT NULL,
    country     VARCHAR(100)  NOT NULL,
    city        VARCHAR(100)  NOT NULL,
    website     TEXT
);

CREATE TABLE IF NOT EXISTS category (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL UNIQUE,
    description TEXT          NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredient (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL UNIQUE,
    description TEXT
);

-- ============================================================
-- Tables avec FK
-- ============================================================

CREATE TABLE IF NOT EXISTS beer (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL UNIQUE,
    description     TEXT,
    price           NUMERIC(6,2)    NOT NULL CHECK (price >= 0),
    alcohol_level   NUMERIC(4,1)    NOT NULL CHECK (alcohol_level >= 0),
    is_alcohol_free BOOLEAN         NOT NULL,
    brewery_id      INTEGER         NOT NULL
                        REFERENCES brewery(id) ON DELETE CASCADE
);

-- Le côté enfant de beer.brewery_id n'est pas indexé automatiquement : cet index
-- sert le filtre ?breweryId= des bières, l'agrégat beerCount des brasseries et
-- le ON DELETE CASCADE depuis brewery.
CREATE INDEX IF NOT EXISTS idx_beer_brewery_id ON beer(brewery_id);

-- ============================================================
-- Journalisation des insertions de bières
-- ============================================================

CREATE TABLE IF NOT EXISTS beer_log (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beer_id     INTEGER         NOT NULL
                    REFERENCES beer(id) ON DELETE CASCADE,
    beer_name   VARCHAR(255)    NOT NULL,
    action      VARCHAR(10)     NOT NULL DEFAULT 'INSERT'
                    CHECK (action IN ('INSERT')),
    logged_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    logged_by   VARCHAR(100)    NOT NULL DEFAULT current_user
);

-- Fonction déclenchée automatiquement à chaque INSERT sur beer
CREATE OR REPLACE FUNCTION fn_log_beer_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO beer_log (beer_id, beer_name, action, logged_at, logged_by)
    VALUES (NEW.id, NEW.name, 'INSERT', NOW(), current_user);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_beer_insert_log
AFTER INSERT ON beer
FOR EACH ROW
EXECUTE FUNCTION fn_log_beer_insert();

CREATE TABLE IF NOT EXISTS beer_review (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade       INTEGER         NOT NULL CHECK (grade BETWEEN 1 AND 10),
    comment     TEXT,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    user_id     INTEGER         NOT NULL
                    REFERENCES "user"(id) ON DELETE CASCADE,
    beer_id     INTEGER         NOT NULL
                    REFERENCES beer(id) ON DELETE CASCADE,
    UNIQUE (user_id, beer_id)
);

CREATE TABLE IF NOT EXISTS brewery_review (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade       INTEGER         NOT NULL CHECK (grade BETWEEN 1 AND 10),
    comment     TEXT,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    user_id     INTEGER         NOT NULL
                    REFERENCES "user"(id) ON DELETE CASCADE,
    brewery_id  INTEGER         NOT NULL
                    REFERENCES brewery(id) ON DELETE CASCADE,
    UNIQUE (user_id, brewery_id)
);

-- thumbnail_url / width / height sont NULLABLE : une ligne peut pointer vers une
-- image externe dont nous ne générons ni vignette ni dimensions (cf. le seed).
-- Les lignes créées par la route d'upload renseignent systématiquement les 4 colonnes.
CREATE TABLE IF NOT EXISTS beer_photo (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           TEXT        NOT NULL,
    thumbnail_url TEXT,
    width         INTEGER     CHECK (width  > 0),
    height        INTEGER     CHECK (height > 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    beer_id       INTEGER     NOT NULL
                      REFERENCES beer(id) ON DELETE CASCADE
);

-- PostgreSQL n'indexe pas automatiquement le côté enfant d'une FK :
-- cet index sert la seule lecture prévue (WHERE beer_id = $1) et le ON DELETE CASCADE.
CREATE INDEX IF NOT EXISTS idx_beer_photo_beer_id ON beer_photo(beer_id);

CREATE TABLE IF NOT EXISTS brewery_photo (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url           TEXT        NOT NULL,
    thumbnail_url TEXT,
    width         INTEGER     CHECK (width  > 0),
    height        INTEGER     CHECK (height > 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    brewery_id    INTEGER     NOT NULL
                      REFERENCES brewery(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_brewery_photo_brewery_id ON brewery_photo(brewery_id);

-- ============================================================
-- Tables de liaison (clés primaires composites)
-- ============================================================

CREATE TABLE IF NOT EXISTS beer_favorite (
    user_id     INTEGER     NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    beer_id     INTEGER     NOT NULL REFERENCES beer(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, beer_id)
);

CREATE TABLE IF NOT EXISTS brewery_favorite (
    user_id     INTEGER     NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    brewery_id  INTEGER     NOT NULL REFERENCES brewery(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, brewery_id)
);

CREATE TABLE IF NOT EXISTS beer_category (
    beer_id     INTEGER NOT NULL REFERENCES beer(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES category(id) ON DELETE CASCADE,
    PRIMARY KEY (beer_id, category_id)
);

CREATE TABLE IF NOT EXISTS beer_ingredient (
    beer_id       INTEGER NOT NULL REFERENCES beer(id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredient(id) ON DELETE CASCADE,
    PRIMARY KEY (beer_id, ingredient_id)
);
